### ISSUE TITLE
rowData does not contain the rownames

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/SummarizedExperiment#2] opened 2017-12-08 10:31 UTC
```r
library(SummarizedExperiment)
example(SummarizedExperiment)
rownames(se) <- paste0("Gene", seq_len(nrow(se)))
rownames(se)[1:10]
##  [1] "Gene1"  "Gene2"  "Gene3"  "Gene4"  "Gene5"  "Gene6"  "Gene7"  "Gene8" 
##  [9] "Gene9"  "Gene10"
rowData(se)
##      feature_id
##     <character>
## 1         ID001
## 2         ID002
## 3         ID003
## 4         ID004
## 5         ID005
## ...         ...
## 196       ID196
## 197       ID197
## 198       ID198
## 199       ID199
## 200       ID200
```

One would expect that the `rownames` of the `rowData` would be equal to `rownames(se)`, given that this is the case for `rownames(colData(se))` and `colnames(se)`.

Session info:

```
R version 3.4.2 Patched (2017-10-30 r73642)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /home/cri.camres.org/lun01/Software/R/R-3-4-branch_release/lib/libRblas.so
LAPACK: /home/cri.camres.org/lun01/Software/R/R-3-4-branch_release/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] SummarizedExperiment_1.8.0 DelayedArray_0.4.1        
[3] matrixStats_0.52.2         Biobase_2.38.0            
[5] GenomicRanges_1.30.0       GenomeInfoDb_1.14.0       
[7] IRanges_2.12.0             S4Vectors_0.16.0          
[9] BiocGenerics_0.24.0       

loaded via a namespace (and not attached):
 [1] lattice_0.20-35         bitops_1.0-6            grid_3.4.2             
 [4] zlibbioc_1.24.0         XVector_0.18.0          Matrix_1.2-12          
 [7] tools_3.4.2             RCurl_1.95-4.8          compiler_3.4.2         
[10] GenomeInfoDbData_0.99.1
```

**Comment by mtmorgan** [comment] 2017-12-08 19:03
I think it's a GRanges thing @lawremi @hpages 
```
> gr = GRanges("chr1:1-5", foo = "a")
> names(gr) = "A"
> gr
GRanges object with 1 range and 1 metadata column:
    seqnames    ranges strand |         foo
       <Rle> <IRanges>  <Rle> | <character>
  A     chr1    [1, 5]      * |           a
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
> mcols(gr)
DataFrame with 1 row and 1 column
          foo
  <character>
1           a
```

**Comment by lawremi** [comment] 2017-12-08 20:35
Are you expecting identical(rownames(mcols(gr)), names(gr))? That's not the
contract. For one thing, names(gr) can contain duplicates, but rownames
should be unique. But I don't see a rationale for it anyway.

**Comment by LTLA** [comment] 2017-12-08 21:59
This was motivated by some users' experiences with transitioning from `SCESet` (based on an `ExpressionSet`) to `SingleCellExperiment` (based on a `SummarizedExperiment`), where `fData(sceset.object)` contains the row names in the resulting data frame but `rowData(sce.object)` does not. This resulted in a few scripts breaking, especially for things using _ggplot2_.

I thought it was fairly reasonable to return the row names with the `rowData`, but I've never actually seen the Bioconductor class contract anywhere (only heard of it every now and then).

**Comment by lawremi** [comment] 2017-12-08 23:46
Just to clarify, I was only referring to the behavior of GRanges. It of course makes sense for SummarizedExperiment to behave like eSet.

**Comment by mtmorgan** [comment] 2017-12-12 19:42
After some discussion, `rowData(se, use.names=TRUE)` returns names (unless there are duplicate rownames, in which case it throws an error), which is semi-documented on `?rowData` as '...' forwarded to `mcols()`.

**Comment by LTLA** [comment] 2017-12-12 20:40
Thanks Martin. I'm surprised that `DataFrame` doesn't support duplicate row names as well (given that they're optional anyway), in which case we wouldn't have to consider this special behaviour.

**Comment by hpages** [comment] 2017-12-12 21:45
In this case DataFrame is mimicking what ordinary data.frame do. Generally speaking we want to stay as close as possible to base R behaviour for low-level things like DataFrame or Rle objects. However in some situations we intentionally allow some divergence e.g. `unlist()`'ing a List derivative doesn't mangle the outer names unlike `unlist()` does on an ordinary list (note that unlisting a named GRangesList is typically how one ends up with a GRanges with duplicated names on which mcols() wouldn't be able to return a DataFrame with rownames). Maybe allowing duplicated rownames could be one of these situations of divergence. This would mean that `as.data.frame()` will sometimes fail but that's a small price to pay for having `mcols()` and `rowData()` return the rownames by default.

**Comment by lawremi** [comment] 2017-12-12 21:52
Consistency was definitely the goal. I'm OK with allowing duplicate rownames though. 

I get the desire for consistency with eSet, but I am a little surprised we are pushing so hard for rownames here when the tidyverse is against them. The users may be better off in the long run storing identifiers in an actual column.

**Comment by hpages** [comment] 2017-12-12 22:03
An important use case though is when the rownames of `mcols(x)` originate from `names(x)`. Yes you can store the transcript ids in a metadata column of the GRangesList object returned by `exonsBy()` but right now they are stored in the names which is quite convenient. Will be nice to have them propagated all the way to the DataFrame returned by `mcols(unlist(grl))`.

**Comment by lawremi** [comment] 2017-12-12 22:24
Agreed that names can be convenient in R. For the tidyverse though, the rownames are not so convenient, because they fall outside of their model.

**Comment by mtmorgan** [comment] 2018-01-26 10:18
Is this issue open, resolved, or ?

**Comment by flying-sheep** [comment] 2018-06-04 08:41
For consistency, we should definitely return rownames by default. It's super confusing that the rownames vanish:

```r
df <- data.frame(..., row.names = ...)
ex <- SummarizedExperiment(..., rowData = df)
rownames(rowData(ex))  # NULL?!
rownames(rowData(ex)) <- ...
rownames(rowData(ex)) # still NULL?!?!
```

**Comment by hpages** [comment] 2018-06-04 16:12
A prerequisite if we want to properly deal with this is to allow duplicate row names in a DataFrame. This is a situation that is a lot more common than people tend to think. Having `rowData()` sometimes succeed and sometimes fail by default is not going to be really satisfying. Also having its semantic drift apart from that of `mcols()` when it's supposed to just be an alias for the latter is going to be confusing.

I just made the following change in S4Vectors: https://github.com/Bioconductor/S4Vectors/commit/6dd5e6187d0ec7f228659791f2d357809027e32e
The next one will be to have `mcols()` propagate the row names by default. I'll wait a couple of days that the above change propagates before doing this.

**Comment by lawremi** [comment] 2018-06-04 18:34
Let's please keep in mind that we are changing the behavior of DataFrame just to support something in SummarizedExperiment. Are we sure that's worth it? 

An alternative approach would be to simply call `make.unique()` on the names prior to making them the rownames. This would preserve the rownames in the case above and behave in accordance with user expectations.

Also, can we make sure that `as.data.frame,DataFrame()` will still succeed when there are duplicate rownames (by making them unique)?

**Comment by hpages** [comment] 2018-06-04 23:09
The change is to allow `mcols()`, not just `rowData()`, to propagate the rownames,

`as.data.frame.DataFrame(x)` now calls `make.unique()` on `rownames(x)` so will still succeed in case of duplicate rownames,

**Comment by lawremi** [comment] 2018-06-05 01:57
Ok, is anyone asking for that though? I could see why it is intuitive in the SE case (see above) but I'm not sure if there is a use case. What do you think about the alternative I suggested?

**Comment by hpages** [comment] 2018-06-05 04:34
It's important to keep in mind that the row names that are expected to be propagated by `mcols(x)` or `rowData(x)` are actually the names of vector-like object `x`. I don't see a lot of value in mangling the original names in order to be able to propagate them to the returned DataFrame. It sounds like an artificial trick to make propagation **technically** possible, and is ignoring the fact that the propagated names are meaningless and useless. I'd rather propagate the original meaningful names.

**Comment by hpages** [comment] 2018-06-05 04:39
Also the use case is the same I mentioned earlier in this issue: with this change `mcols(unlist(exonsBy(txdb)))` will have meaningful rownames (the transcript names).

**Comment by lawremi** [comment] 2018-06-05 16:48
I get that names can be duplicated, but not rownames, and so do many other R users, so mangling would be an expected behavior, as @flying-sheep mentioned.

Transcript names as rownames is not really a use case, because it does not motivate the use of the rownames. 

Given that the tidyverse is rejecting rownames, we might want to just keep things consistent with data.frame and not worry about putting them on `mcols()` in the general case.

**Comment by hpages** [comment] 2018-06-05 18:55
Mangling might be expected by some users but that still doesn't make the mangled names useful for anything.

**Comment by lawremi** [comment] 2018-06-05 19:53
And rownames are not that useful, period, so I just think we should carefully consider changes like these.

**Comment by hpages** [comment] 2018-06-05 20:08
It is carefully considered.

But you are arguing in favor of doing name mangling instead of allowing propagation of the real names. How is the fact that tidyverse is rejecting rownames an argument in favor of name mangling? This is an argument in favor of ignoring the row names which was actually the philosophy behind having `mcols()` and `rowData()` **not** propagating them by default. What we are discussing here is to propagate the row names by default because some people (not me) seem to care about them. The only 3 options I can think of to deal with duplicate row names are: (1) fail when there are duplicate names (Martin's current workaround in SummarizedExperiment); (2) mangle them (your proposal); (3) have DataFrame support duplicate row names so by default `mcols()` and `rowData()` never fail and propagate the real names (my proposal).

Again I've never seen any use case where the mangled names (produced by `data.frame()` or `unlist()` or [RSQLite::dbGetQuery()](https://github.com/r-dbi/RSQLite/issues/259)) are a good thing. Even if you don't see having duplicate transcript names in the row names as something useful, and I tend to agree with that, my point is that it's still better than having mangled transcript names there (which are indistinguishable from valid transcript names so this is the worst case scenario). The name mangling game in base R is a terrible feature.

Finally note that you said earlier in this thread (Dec 12) that you were "OK with allowing duplicate rownames" but nothing happened after that. When @mtmorgan asked you on Jan 26 what you wanted to do about this we got no answer. So I thought I would just go ahead and do it (i.e. allow duplicate rownames in a DataFrame). One less thing for you to take care of so you should be happy!

**Comment by lawremi** [comment] 2018-06-05 20:30
Yea, I am OK with it if it is indeed the best solution. My point was that rownames are usually not so useful, so there is not a strong impetus for changing longstanding behavior. It's not a direct argument for name mangling. 

The name mangling in base R is probably a compromise to be forgiving while at the same time preserving the guarantee that rownames are unique. Mangled rownames are not useful, but at least the guarantee is preserved and the user is not inconvenienced by a potentially irrelevant error.

It looks like SummarizedExperiment is unique in that by default it takes its names from the rownames on the `@rowData`. The user therefore expects them to be preserved. Why not just keep the rownames on `@rowData`?

**Comment by hpages** [comment] 2018-06-05 20:46
SummarizedExperiment takes its names (and row names) from `@NAMES`. There is no `@rowData`. `rowData()` and `mcols()` are both going for the DataFrame stored in `@elementMetadata` and stick `@NAMES` on-the-fly on it (as the row names) before returning it to the user.

But more importantly the user should not (and generally does not) make expectations based on internal representation details so where/how the names/rownames are stored exactly is irrelevant. We're discussing semantic here not implementation details.

**Comment by lawremi** [comment] 2018-06-05 20:51
Sorry for using the wrong slot name. From the above, the user had rownames on the `rowData=` argument to constructor and thus expected them to be preserved on the object returned from `rowData()`. From the user's perspective, those are the same thing. Internally, we strip the names off the thing that is stored in `@elementMetadata`. Couldn't we just not do that, at least in this case?

**Comment by hpages** [comment] 2018-06-05 21:12
Again, the original discussion is about semantic, not implementation details. Whether we strip the **row names** off the DataFrame that we store in `@elementMetadata` and put them in the `@NAMES` slot is an implementation detail. This is not unique to SummarizedExperiment. We actually do this (i.e. the stripping off) for **all** Vector derivatives. I won't start the long story of why we do this because I'm not sure it would help here (not surprisingly it's related to the fact that DataFrame didn't support duplicate row names so far). Now that DataFrame supports duplicate row names we wouldn't need to do this strip off anymore. However I'm not planning to change that.

**Comment by lawremi** [comment] 2018-06-05 21:27
I'll stop making suggestions about how to implement it. The proposed semantic is:

If there are rownames on the passed `rowData`, those will be taken as the default names on the object, and also be the rownames on the DataFrame returned from `mcols()` and `rowData()`. If the user provides names to the constructor, then those are just the names. They do not become the rownames on the return value of `mcols()`.

**Comment by hpages** [comment] 2018-06-05 23:11
I'm not sure you're serious with this proposal.

1. The current semantic is that the row names on the DataFrame passed to the `mcols()` or `rowData()` setter are always ignored (and this is for all Vector derivatives in the case of the `mcols` setter). They never alter the names of the object. I don't think we want to revisit that, but if we do, that would need to be carefully considered.
2. For a SummarizedExperiment object `x`, `names(x)` == `rownames(x)` == `rownames(assay(x))` == `mcols(x, use.names=TRUE)` == `rowData(x, use.names=TRUE)`. All these are **the same character vector** (or `NULL`). Deviating from that is not going to help make these objects feel more intuitive or more friendly, all the contrary. In particular when you say "then those are just the names", you're suggesting that now `names(x)` or `rownames(x)` or `mcols(x, use.names=TRUE)` or `rowData(x, use.names=TRUE)` could return different things depending on **how** exactly the user set the names or row names on the object (i.e. via the constructor, or via `rownames<-`, `names<-`, `rowData<-`, etc...). Sounds like it would bring a lot more trouble than good.

**Comment by lawremi** [comment] 2018-06-05 23:48
Re-reading the thread, it does look like there is an expectation for `rownames(x)` to be the same as `rownames(mcols(x))` because of the way `colData(x)` behaves. We probably should have stayed away from messing with the rownames due to the inconsistency between data.frame and matrix, but now the cat is out of the bag. I don't think I'll be able to convince you to mangle names like R does, so it looks like we're just going to have to deviate from R here.

**Comment by hpages** [comment] 2018-06-06 00:57
If that can help you make feel better about this particular deviation, here is another deviation but for the col names:
```
> as.data.frame(list(aa=1:3, aa=21:23))
  aa aa.1
1  1   21
2  2   22
3  3   23

> as(list(aa=1:3, aa=21:23), "DataFrame")
DataFrame with 3 rows and 2 columns
         aa        aa
  <integer> <integer>
1         1        21
2         2        22
3         3        23
```
This one has been around for many years and was not decided or implemented by me. AFAIK nobody got hurt by it so far so it looks like those deviations are not such a big deal after all (as long as they bring something positive).

**Comment by hpages** [comment] 2018-06-07 02:27
FWIW commit 4b4f03cd353414bc8a3a76cee150eae8562da9d2 actually seems to break some packages in devel:

  https://bioconductor.org/checkResults/3.8/bioc-LATEST/diffcyt/malbec1-buildsrc.html

We should revert that commit once `mcols()` switches to `use.names=TRUE` by default. Then those errors will go away.

**Comment by hpages** [comment] 2018-06-08 03:41
Here is my final change concerning this issue: 1cf9771ecdacecbedd250fda9606b1809e40c329 This is SummarizedExperiment 1.11.5.

Can we close this now?

**Comment by LTLA** [comment] 2018-06-08 09:54
Yep, looks like it works for me. So to sum up:

- `rowData` now returns a `DataFrame` with row names by default.
- Row names can now be duplicated in `DataFrame`.
   - Names in general can be duplicated, across the entire BioC S4 ecosystem?
- Also, column names can be duplicated, which I didn't really know until now.

**Closed** 2018-06-15 18:44 UTC
